### ISSUE TITLE
Hi-Ether Meetup - Block 2 を開催する / 2018年4月13日(金) / DMM.comラボ

### ISSUE THREAD

**Issue by june29** [hi-ether/community#2]
### やること

- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [x] LT スピーカーを決める
- [x] タイムテーブルをつくる
- [x] 参加登録を開始する
- [x] 食べもの・飲みものを手配する
- [x] 会場の「ゴミの捨て方」を確認して備えておく
- [x] 前日〜当日あたりに諸情報を含めたリマインドをする
- [x] 開催する！

### 担当

- 会場予約 1 人 : @amachino 
- コンテンツ委員 1〜2 人 : @amachino  @kooooohe 
- 受付 3 人 : @yaggytter @areph @kooooohe
- 会計 1 人 : @june29
- 司会 1 人 : 
- 飲食手配 1〜2 人 : @yuzushioh
- タイムキーパー 1 人 : @amachino 
- イベントページ準備 1 人 : @amachino

**Comment by yaggytter** [comment]
いつもありがとうございます！
どれがよいのかわからないのですが、お手伝いさせていただきたいです！
よろしくお願いいたします。

はじめての会場なのですが、受付とかをご教示いただけますと幸いです。

**Comment by june29** [comment]
@yaggytter ありがとうございます！

まだ空き枠だらけで選びたい放題なので、興味のあるやつ・今後の糧になりそうなやつ・得しそうなやつ、どれでもお好きなものをどうぞ :relaxed:

受付のいいところは、いっしょに受付を担当する人たちと仲良くなれることと、参加者のみなさんの顔と名前を一致させやすくなること、あたりです！

**Comment by yaggytter** [comment]
@june29 
ありがとうございます！
では、受付させていただければ幸いです。
他にも当日必要な役割あればやらせていただきたいと存じます。
よろしくお願いいたします！

**Comment by wshino** [comment]
こちら、4点ほど確認したいことがあります。お手すきの際に教えていただけますと幸いです。

- 入館QRコードを発行しますが、techplayなどで一斉メール配信できますか？
- 録画はしますか？三脚は用意できます。
- 案内紙の作成と印刷→画像があればこちらで印刷します。
- ディスプレイのコネクタはVGA, DVI, HDMI, USB-C以外に用意するものがあればお伝えいただけると。

**Comment by june29** [comment]
ぼくがわかりそうなものを回答します！

> techplayなどで一斉メール配信できますか？

TECH PLAY のイベント管理ページに「参加者に連絡」という機能があるので、これでできそうです :v:

> ディスプレイのコネクタはVGA, DVI, HDMI, USB-C以外に用意するものがあればお伝えいただけると。

は登壇者次第ですかねぇ。ただ、これだけ選択肢があれば充分に思えまして、会場情報として登壇者のみなさんに「これらのインターフェイスがあります」とお伝えしておくだけでよさそうです。ぼくがこれまで登壇してきたイベントだと、事前に教えてもらえるのは「接続インターフェイス」と「スクリーンの縦横比」というケースが多かったです。

**Comment by kazush-m** [comment]
ビデオカメラ2台、三脚2本、ワイヤレスマイクを持参します。ワイヤレスは胸元につけていただくタイプです。照明はなし。ワイヤレスマイクをつけないとカメラ周辺の関係ない音を拾ってしまいますので。

**Comment by kazush-m** [comment]
ビデオ撮影はスピーカー中心でいく予定です。投影されたスライドも一応一緒に撮りますが、スライドが投影されたスクリーンに露出を合わせるとスピーカーが暗くなってしまい、スピーカーに合わせると投影された画面が真っ白になって見えない、というのが普通ですので。編集で二台のカメラの画像を切り替えるなどなどしましてお話とスライドの進行はわかるようにします。

**Comment by wshino** [comment]
@kazush-m ありがとうございます。ワイヤレスマイクと、会場スピーカー用のマイクは別ということでしょうか？

**Comment by kazush-m** [comment]
別です。ビデオカメラに飛ばす為だけのマイクです。

**Comment by kooooohe** [comment]
まだ、空きがあれば受付をお手伝いさせていただければと思います。
いかがでしょうか？ :)

**Comment by june29** [comment]
@kooooohe さん、ぜひに！

ちょうど LT スピーカーの募集をぼちぼち始めたいな〜と思っていたところです。いっしょにやりませんか？ :smiley:

**Comment by june29** [comment]
@kooooohe さんがもりもりと進めてくださって LT スピーカーが決まったので :white_check_mark: しました :v:

引き続き、食べ物・飲み物の手配をやってくれる人を募集します :pray: :pray: :pray:

**Comment by mach** [comment]
私タイムテーブル作りますね

**Comment by june29** [comment]
@kooooohe さんが受付もお手伝いしてくれることになったので、だいぶ磐石になりました :muscle:

事前の準備に関しては安全水域に達したと思います！

**Comment by areph** [comment]
こんにちは。参加できる見通しが着いたので運営側のお手伝いをしたいのですが、もう手は必要ないでしょうか？

**Comment by june29** [comment]
@areph さん、ありがとうございます！では受付をいっしょにやってほしいです :smiley:

それと、Hi-Ether の Slack で @areph さんがどの人か把握したいので、Slack で @june29 に適当に話しかけてくださいますよう、よろしくお願いします :wink: :dash:

**Comment by mach** [comment]
https://techplay.jp/event/664948?pw=jmngr5yR

**Comment by hrnkoji** [comment]
DMM社内の人間なので会場の設営など手伝います。
で、質問なのですがビデオカメラの撮影って配信とかしますか？

**Comment by june29** [comment]
@hrnkoji さん、この度はお世話になります :pray:
ビデオカメラ関連は @kazush-m さんがいろいろと考えてくれているので連携をお願いしたいです :dash:

**Comment by kazush-m** [comment]
@hrnkoji さん　お世話になります！
ビデオカメラ持参で行く予定ですが、配信は考えておりませんでした。もちろんやるのは可ですが、もしかしてDMMさんの方で撮影から配信まで全部していただけるようでしたらお願いしちゃった方がよいと思っております...

**Comment by hrnkoji** [comment]
@june29 @kazush-m こちらこそお世話になりますー
@kazush-m DMM側で全部やるとなると担当の部署にお願いしないといけないので、どっちなのかなーという確認でした。kazush-mさんに全部お願いしてもいいですか？

**Comment by kazush-m** [comment]
もちろんokです😃

**Comment by kazush-m** [comment]
iPadでのライブ配信のために現場でWi-Fi 使わせていただけると助かります！

**Comment by hrnkoji** [comment]
Wi-Fi使えます。ゲスト用のがあります。

**Comment by wshino** [comment]
アルコールが30缶程度ありましたので冷蔵庫で冷やしておきます。

**Comment by mach** [comment]
TODO:

- 入館用QRコードを参加者にメールで伝える @mach

**Comment by yuzushioh** [comment]
@wshino アルコールは100缶くらいあれば大丈夫ですかね？ソフトドリンクも適当に買っておきます。

**Comment by wshino** [comment]
2140からお片づけして、2200にはフロアを退出できるようにしましょう。

**Comment by june29** [comment]
### 無事に開催できました！

発表者のみなさん、運営に関わったみなさん、参加者のみなさん、どうもありがとうございました。お疲れさまでした。

### 参加人数

TECH PLAY 上のデータでは「定員 100 人 / 申込 95 人 / 出席 71 人」でした。

### 会計

- ドミノピザ : 37,130 円
- カクヤス : 18,070 円
- 合計 55,200 円

上記を支払って約 3,000 円ほどの黒字だったので、懇親会費の 1,000 円を払ってくださった方が 58〜60 人くらいいたのだろう、というざっくりとした収支報告になります。厳密な管理は目指しておらず、行っていません :wink:
