### ISSUE TITLE
Hi-Ether Meetup #4 Fukuoka を開催する / 2018年5月27日(日) / GMOペパボ（福岡）

### ISSUE THREAD

**Issue by amachino** [hi-ether/community#3]
福岡でミートアップを行う機運が高まっている！
https://hi-ether.slack.com/archives/C8508FABB/p1522655738000005

参考
https://github.com/hi-ether/meetup/issues/2

**Comment by ayasamind** [comment]
やること
  - [x] 日程を決める
  - [x] 会場を決める
  - [x] スピーカーを決める
  - [x] LT スピーカーを決める
  - [x] タイムテーブルをつくる
  - [x] 参加登録を開始する
  - [x] 食べもの・飲みものを手配する
  - [x] 会場の「ゴミの捨て方」を確認して備えておく
  - [x] 前日〜当日あたりに諸情報を含めたリマインドをする
  - [x] 開催する！

担当
  会場予約 1 人 : 
  コンテンツ委員 1〜2 人 : 
  受付 3 人 : 
  会計 1 人 : 
  司会 1 人 :
  飲食手配 1〜2 人 :
  タイムキーパー 1 人 : 
  イベントページ準備 1 人 :

**Comment by june29** [comment]
おつかれさまでございました！

「-829円」把握しました。負担してくださった方、ありがとうございます。LINE Pay や Kyash でよければシュッと送ることもできます！
