### ISSUE TITLE
Hi-Ether Meetup #3 Tokyo を開催する / 2018年5月17日(木) / GMO Yours

### ISSUE THREAD

**Issue by june29** [hi-ether/community#4]
### やること

- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [x] LT スピーカーを決める
- [x] タイムテーブルをつくる
- [x] 参加登録を開始する
- [x] 食べもの・飲みものを手配する
- [x] 会場の「ゴミの捨て方」を確認して備えておく
- [x] 前日〜当日あたりに諸情報を含めたリマインドをする
- [x] 開催する！
- [x] 収支報告をする

### 担当

- 会場予約 1 人 : @june29
- コンテンツ委員 1〜2 人 : @amachino @june29 @kooooohe 
- 受付 3 人 : @yaggytter @kooooohe + @takei-shg +GMOペパボから数人
- 会計 1 人 : @june29
- 司会 1 人 : @amachino @june29
- 撮影・配信 0〜2 人 :  @kazush-m
- 飲食手配 1〜2 人 : @june29 とGMOペパボのメンツ
- タイムキーパー 1 人 : なし (今回はゆるめに運用)
- イベントページ準備 1 人 : @yaggytter

**Comment by june29** [comment]
ひとまずこれを `Block #4` としてみたけれど、福岡開催もあることだし「ナンバリングどうする？」のお話をしておくといいですかねぇ。

「開催が決定したものから順に採番する」がいちばん素直でわかりやすいかしら。

@ayasamind @amachino この Issue で扱う東京開催を `Block #4` にして、福岡開催を `Block #3` とするのでいかがでしょ？

(そうすると、たまたまだけどこのリポジトリの Issue 番号とも揃って非常にわかりやすいというメリットがある :smiley:)

**Comment by kazush-m** [comment]
撮影・配信　@kazush-m　（お差し支えなければ...控えめな立候補）

**Comment by amachino** [comment]
今後 Tokyo 以外でもミートアップが自律的に立ち上がっていける仕組みを整えたいですよね。

ミートアップの採番（チェーン）としては１つに統一された方がステキに思うんですが、タイトルに開催場所（Tokyo なのか Fukuoka なのか）は入ってないと流石に分かりにくいかな？

あとは、不正なミートアップ開催（Hi-Ether の名前を使って情報商材屋が怪しいミートアップを開く等）に対する耐性を持たせる仕組みが必要だと思っていて、例えば、イベントページには必ず「前回のミートアップ」として前回のイベント URL を入れるようにして、不正なミートアップの場合には、その後に繋げないようにするとか。

その際、「あるミートアップが不正か否か」を、何らかの方法でコンセンサスを取る必要あり。

**Comment by kooooohe** [comment]
そろそろLT枠募集の時期だと思うのですが、私が募集かけちゃってもよろしいでしょうか!?
その場合前回どうよう3~4枠の募集って感じですかね？

**Comment by june29** [comment]
@kooooohe さん、声かけありがとうございます！めちゃ助かります :joy:

ちょいとコンテンツ全体に不確定な部分があるので枠数を明示しづらいのが現状なのですが、いずれにしても LT は募集したいのでそのように進めていただけますでしょうか :pray: :pray: :pray:

**Comment by innovation-yagasaki** [comment]
もしよろしければ、今回も受付やらせていただければ！
そして、もしあれでしたら、参加登録ページの準備とかもやります！

**Comment by june29** [comment]
@innovation-yagasaki さん〜 :heart_eyes: めちゃ助かります！ぜひお願いしたいです :pray:

**Comment by kooooohe** [comment]
@june29 さん
なるほど。
開催1週間前なので、枠数が確定してから募集をかけたい気持ちもありますね…。
いつくらいに、枠数決まりそうかってわかりますかね？

**Comment by june29** [comment]
@kooooohe さん、ありがとうございます :dolphin:

たとえば「5枠！」と言って募集しても応募が 3 つしかこなかったら 5 枠と決めた意味が無効化されてしまうので、とりあえず募集をはじめちゃって応募状況を見ながらいろいろを判断するのがベターかな、と思った次第でした。っていうのをちゃんと説明したらよかったですね、ごめんなさい :sob:

-----

昨晩に「15 分の講演」がひとつ決まったので、LT は最大で 5 枠くらいで！残りの時間は懇親タイムにしちゃいましょう :muscle:

**Comment by kooooohe** [comment]
@june29 さん
なるほど！わかりやすい説明ありがとうございます！
では、最大5枠募集します！的な感じで、前回と同じように募集かけちゃいますね〜 :)

**Comment by amachino** [comment]
17日の準備全然手伝えていなくて恐縮なんですが、手伝えることあれば言ってください！

**Comment by yaggytter** [comment]
↑間違えて会社のアカウントで入ってました；

@june29 
イベントページの公開ありがとうございます！
当日は受付もやらせていただきます！ちょっと早めに行きます！

**Comment by june29** [comment]
@yaggytter なるほど複数アカウント運用 :joy:

イベントページは雛形を用意してもらえたので、ぼくは最後に会場情報なんかを詰め込むだけで済んで楽チンでした！

受付もぜひお願いしたいです！受付経験ある人がひとりでもいてくれるとだいぶ安心です :whale:

**Comment by june29** [comment]
- 2018 年 5 月 15 日 (火) に、入館のためのゲストカード発行などをやりました
- 飲食の手配は 5 月 17 日 (木) の午前に、最新の参加申し込み人数を見ながらやります
- GMO ペパボからは、ぼくを含めて少なくとも 3 人は運営の人手を提供します

**Comment by kooooohe** [comment]
@june29 ギリギリになりましたが、今回も受付お手伝いさせてください！

**Comment by june29** [comment]
@kooooohe さん〜 :heart_eyes: 今回もよろしくです、頼りにしています :pray:

**Comment by yujikuroki** [comment]
@june29 はじめまして！お邪魔にならなければすこし早めにお伺いしてなんでも雑用させて頂きたいと思うのですが需要ありそうでしょうか？😀

**Comment by takei-shg** [comment]
受付で参加させてください、よろしくお願いいたします。

**Comment by june29** [comment]
食べ物と飲み物を手配しました〜！ :pizza: :poultry_leg: :beers: :cocktail:

**Comment by june29** [comment]
無事に開催できてよかった。話し手のみなさん、お手伝いいただいたみなさん、参加者のみなさん、ありがとうございました〜！:relaxed:

のちほど参加者数や収支の報告をして、そしたら Close します :dash:

**Comment by yaggytter** [comment]
今回も運営お手伝いさせていただき、ありがとうございました！
福岡は難しいですが、東京のイベントは引き続きお手伝いさせていただければ幸いです！

**Comment by kazush-m** [comment]
皆様ありがとうございました＆お疲れ様でした。今回も大変有意義でした。動画は今後下記で公開いたします。前回#2の動画もUPLOADしなおしました。（過去に公開した動画もそのままになっていますので、ブログ等に埋め込んで頂いているものが消えることはありません。）
https://www.youtube.com/channel/UCodxninAQeQudwlCsdKg_dA

**Comment by june29** [comment]
定員 60 名 / 参加登録 51 名 / 参加 47 名 / 懇親会参加は 42 名くらい

今回もキャンセル率がとても低くて運営に関わる側としては大変ありがたいことです :pray:

ピッザ 20,476 円
飲み物 24,881 円

今回は @june29 が飲食の手配を担当し、クレジットカードで支払ったので、集まったお金から 25,000 円をもらっておきました。うまく証明できるものがないので「信じてください」と言う他ない…！

ほいで、これまでの流れで @june29 が管理している Hi-Ether の運営資金 (？) 的なものは、現在だいたい 23,000 円ほどあります。これがあんまり増えてもアレなので、新しいロゴができたあとに「ミートアップ参加者用名札の台紙の印刷費」「名札ケース購入費」とかに当てられるといいかなあ、と思っています！

![money](https://user-images.githubusercontent.com/3970/40241059-f9ec6dae-5af4-11e8-8137-aa53f176ad92.jpg)

**Comment by june29** [comment]
ああ、あらためて https://github.com/hi-ether/community/issues/4#issuecomment-390229146 を見たら完全に計算を間違えている…

ぼくは「25,000 円」じゃなくて「45,000 円」をもらわないと大赤字ですね :innocent:
というわけで追加で 20,000 円をもらって、Hi-Ether 袋に入っているのは 3,000 円ほどです！お騒がせしました… :bowing_man: :sweat_drops:

こんなぼくがお金の管理をしているのやばい！もっと FinTech したい！ :dolphin:
