### ISSUE TITLE
ミートアップの開催方針の初版をつくる

### ISSUE THREAD

**Issue by june29** [hi-ether/community#5]
### 概要

@amachino さんが https://github.com/hi-ether/community/issues/4#issuecomment-381374486 に書いてくれたようなトピックを独立して扱う Issue にします :muscle:

### 目的

「お堅いルールをどんどん増やしてガチガチにしていきたい」という気持ちはひとつもなくて、今後のミートアップ開催について

- 都度で考えなきゃいけないことを減らして運用を楽にしたい
- 参加者のみなさんが安心して参加できるように、最低限の安全は守りたい

というあたりを目指してやっていきたいです :dolphin:

### やること

- [ ] なにをもって「Hi-Ether のミートアップです」と認定するのかを決める
- [x] これまで `Block #1` `Block #2` としてきたような、ナンバリングの方針を決める
- [x] 各ミートアップの命名規則を決める (イベント名に地名を含める？等)

他にも思い付いたら足します〜 :dash:

**Comment by nakajo2011** [comment]
- このgithubもopen projectなのでいっそのことIssueのURLを載せるとか。
- https://keybase.io/ という個人向けPKIサービスがあって、この中にチームもあるのでこの辺と組み合わせてkeybaseのClaimと紐づけて開催者の認証を第3者が確認できるようにするとか。

**Comment by june29** [comment]
@nakajo2011 さん、ご意見アンド情報ありがとうございます〜 :heart_eyes:

-----

「やること」のスコープを最初に大きくしてしまって、なかなか進められなくなってしまったところがあるので(反省)、ちょっとスコープを小さくしてタスクを Done していこう… :muscle:

まず直近で旨みがあるのは「ナンバリング」「イベント名」なので、これを詰める。そのために案を出しますぞ。

**Comment by june29** [comment]
### これまで

- `Hi-Ether Meetup - Block #0`
- `Hi-Ether Meetup - Block #1`
- `Hi-Ether Meetup - Block #2`

ぜんぶ Tokyo 開催で、0 からナンバリングを始めて 1 ずつインクリメントしてきた。

-----

### これから 案1

全体のナンバリングはこれまで通りで、うしろに「開催地」をつける。

- `Hi-Ether Meetup - Block #10 Tokyo`
- `Hi-Ether Meetup - Block #11 Fukuoka`
- `Hi-Ether Meetup - Block #12 Sapporo`

わりとシンプル。

### これから 案2

全体のナンバリングはこれまで通りで、うしろに「開催地」と「そこでの n 回目」をつける。

- `Hi-Ether Meetup - Block #10 Tokyo3`
- `Hi-Ether Meetup - Block #11 Fukuoka2`
- `Hi-Ether Meetup - Block #12 Sapporo1`

各開催地で何回目の開催なのかがわかる。けど、ナンバリング体系が 2 つになるので少し複雑。

高専カンファレンス http://kosenconf.jp/ はこの形式。

### これから 案3

全体のナンバリングをやめて、開催地ごとにナンバリング。

- `Hi-Ether Meetup - Tokyo#3`
- `Hi-Ether Meetup - Fukuoka#2`
- `Hi-Ether Meetup - Sapporo#1`

地域Ruby会議 http://regional.rubykaigi.org/ はこの形式ですね。

**Comment by june29** [comment]
直感的には「案1」がシンプルで好み。せっかくなのでひとつのチェーンを全体で大事につないでいきたい気持ちもある。

**Comment by amachino** [comment]
全体で１つの採番（チェーン）とするのに賛成 ⛓ 

表記上、冗長なので案１から「- Block」を取って、

• `Hi-Ether Meetup #10 Tokyo`
• `Hi-Ether Meetup #11 Fukuoka`
• `Hi-Ether Meetup #12 Sapporo`

はどうですかね。「#」を「Block Number」と呼ぶことにして。
ちゃんと #0 から始まってるしw

**Comment by june29** [comment]
https://github.com/hi-ether/community/issues/5#issuecomment-384349562 よさそう！！！:star2:

**Comment by ayasamind** [comment]
あ、その前に5/27の福岡があるので、福岡が

- Hi-Ether Meetup #5 Fukuoka
メルカリの方が 

- Hi-Ether Meetup #6 Tokyo

で大丈夫ですかね？

**Comment by june29** [comment]
いま `#0` `#1` `#2` と開催してきたので、今後の開催日順でいうと

- `Hi-Ether Meetup #3 Tokyo` @ 渋谷 セルリアンタワー
- `Hi-Ether Meetup #4 Fukuoka` @ 福岡 天神プライム
- `Hi-Ether Meetup #5 Tokyo` @ 六本木 メルカリ

こうかな！

**Comment by june29** [comment]
### ミートアップの命名規則とナンバリング

@amachino さんが書いてくれた https://github.com/hi-ether/community/issues/5#issuecomment-384349562 の内容でいきましょう！直近 3 回分については https://github.com/hi-ether/community/issues/5#issuecomment-384530714 で決まり、とします。

### なにをもって「Hi-Ether のミートアップです」と認定するのか

この Issue の冒頭で「やること」のひとつとして書いた

> なにをもって「Hi-Ether のミートアップです」と認定するのかを決める

は、現時点でパリッとした実装案がない！この Issue を Close できないままダラダラしちゃうのもうれしくないので、これは別途お話することにして、ミートアップの命名規則が決まったことを祝福しながら Issue を Close しちゃいます :dash:
