### ISSUE TITLE
Hi-Ether Meetup #5 Tokyo を開催する / 2018年6月12日(火) / メルカリ

### ISSUE THREAD

**Issue by zaq1tomo** [hi-ether/community#9]
### やること

- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [x] LT スピーカーを決める (やらない、と決めたので完了)
- [x] タイムテーブルをつくる
- [x] 参加登録を開始する
- [x] 食べもの・飲みものを手配する (メルカリスポンサー)
- [x] 会場の「ゴミの捨て方」を確認して備えておく
- [x] 前日〜当日あたりに諸情報を含めたリマインドをする
- [x] 開催する！
- [x] 収支報告をする
- [x] 参加者人数を把握する
- [x] 参加者名簿を作成する（名前+所属）

### 担当

- 会場予約 1 人 : @zaq1tomo
- コンテンツ委員 1〜2 人 : @amachino 
- 受付 3 人 : @yujikuroki @kooooohe @yaggytter @takei-shg 
- 会計 1 人 : @june29 
- 司会 1 人 :
- 撮影・配信 0〜2 人 : @kazush-m 
- 飲食手配 1〜2 人 : @zaq1tomo 
- タイムキーパー 1 人 :
- イベントページ準備 1 人 : @amachino

**Comment by amachino** [comment]
今回のスピーカー枠（20分）× 2 は

- メルカリさんから１名
- Curvegrid の Jeff さん

が発表していただけるとのこと！

**Comment by june29** [comment]
どうも！これまでの開催は、だいたい下記のものをベースに準備してきたんですが、今回の開催に向けての現状ってどんな感じでしょ…？

手伝えることがあったら手伝いますのでよろしくお願いします！

```
### やること

- [ ] 日程を決める
- [ ] 会場を決める
- [ ] スピーカーを決める
- [ ] LT スピーカーを決める
- [ ] タイムテーブルをつくる
- [ ] 参加登録を開始する
- [ ] 食べもの・飲みものを手配する
- [ ] 会場の「ゴミの捨て方」を確認して備えておく
- [ ] 前日〜当日あたりに諸情報を含めたリマインドをする
- [ ] 開催する！
- [ ] 収支報告をする

### 担当

- 会場予約 1 人 :
- コンテンツ委員 1〜2 人 :
- 受付 3 人 :
- 会計 1 人 :
- 司会 1 人 :
- 撮影・配信 0〜2 人 :
- 飲食手配 1〜2 人 :
- タイムキーパー 1 人 :
- イベントページ準備 1 人 :
```

**Comment by june29** [comment]
@zaq1tomo さん、当初の予定通りに 6 月 12 日 (火) の夜にメルカリさんに伺うってことで大丈夫でしょうか…？？？ :smiley:

**Comment by zaq1tomo** [comment]
@june29 さん宜しくお願いします！

```
### やること

- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [ ] LT スピーカーを決める
- [ ] タイムテーブルをつくる
- [ ] 参加登録を開始する
- [x] 食べもの・飲みものを手配する (メルカリスポンサー)
- [x] 会場の「ゴミの捨て方」を確認して備えておく
- [ ] 前日〜当日あたりに諸情報を含めたリマインドをする
- [ ] 開催する！
- [ ] 収支報告をする
- [ ] 参加者人数を把握する
- [ ] 参加者名簿を作成する（名前+所属）

### 担当

- 会場予約 1 人 : @zaq1tomo
- コンテンツ委員 1〜2 人 :
- 受付 3 人 :
- 会計 1 人 :
- 司会 1 人 :
- 撮影・配信 0〜2 人 :
- 飲食手配 1〜2 人 :
- タイムキーパー 1 人 :
- イベントページ準備 1 人 :
```

という感じです。
ビルへの申請のため、やること２つ追加させていただきました！

当日の入館オペレーションに関しては、

```
xx時xx分開場、xx時xx分開始の予定です。

六本木ヒルズ森タワーLL階にある専用カウンターにて、お名前の確認と名刺2枚の提示をしていただき、

入館シールを持参の上、18Fイベント会場までお越しください。

xx時xx分以降の受付につきましては、LL階にある受付カウンターにて弊社名をお伝えいただき、

入館証を発行の上、18Fイベント会場までお越しください。1
```

という旨のアナウンスをしていただければと！

**Comment by june29** [comment]
わーお、さっそくありがとうございます！この Issue の概要欄 (いちばん上のところ) に最新の状況を反映させてみました。ここを更新していく感じにしたいな〜と :bulb:

> 食べもの・飲みものを手配する (メルカリスポンサー)

:heart_eyes: :heart_eyes: :heart_eyes:

**Comment by june29** [comment]
スピーカー探しをやってくれた @amachino さんの名前を「コンテンツ委員」のところに入れておきました。飲食については実質 @zaq1tomo さんが担当ということでそのようにしました。

あとは、すぐにやった方がよい順に、

- コンテンツとして LT を取り入れるならすぐにでも募集しなきゃ！
  - LT なかったらなかったで懇親タイムを長めにするのも個人的にはアリだと思っています
- イベントページを用意して参加登録を開始する
- 当日に受付や会計を担当する人を募集して 3 人くらい集めておく

って感じですかね。というわけで、もろもろ手伝ってくれる方を募集します！なにとぞ :pray:

**Comment by june29** [comment]
@yujikuroki やったー、はちゃめちゃに心強いです！ぜひ受付をお願いいたします :pray:

印刷物については @zaq1tomo さんとも軽く認識合わせしておけるとよさそうです。会場側の貼り物のルールとかあるかもしれませんので！

**Comment by zaq1tomo** [comment]
いつもHi-etherでは受付を行っていますか？？

**Comment by zaq1tomo** [comment]
では今回は、

- LL階のロビーで以下を確認する（2人）
  - Hi-Etherのメンバーであること
  - 名刺2枚の提示
  - （うち1枚の提出）
  - 名簿のチェック
  - 入館シール発行

- 18Fの会場で以下を確認する（2人）
  - 参加費の回収（？）

というフローが良いかもしれません！

**Comment by kooooohe** [comment]
今回も受付やら、手伝えることがありましたらお手伝いさせていただければと思います！:)

**Comment by yaggytter** [comment]
わたくしも、また下受付担当などやらせていただきます！

**Comment by amachino** [comment]
ちょうど日本に来ている ConsenSys の Jim さんが、ショートトークしてくれるとのことです！

>  コンテンツとして LT を取り入れるならすぐにでも募集しなきゃ！
LT なかったらなかったで懇親タイムを長めにするのも個人的にはアリだと思っています

スピーカー３名いるので、今回 LT なしでスピーカー × 3 + 懇親会でいいかもですね

**Comment by june29** [comment]
スピーカー 3 名にゆっくりしゃべってもらって、LT なしでいきましょう！今からだとなかなか厳しいと思いますので :joy:

もしここを見ていて「わたしもしゃべりたい！」という人がいたら個別に相談したいので声かけてください〜 :wave:

**Comment by june29** [comment]
@zaq1tomo さん

> 食べもの・飲みものを手配する (メルカリスポンサー)

これって費用はどうなりますかね…？それによって懇親会の徴収をどうするか変わってきて、受付のフローにも関わってくると思ったので確認させてください :pray: :dash:

**Comment by kazush-m** [comment]
今回も撮影・配信でご協力したく思います。開始の1時間前くらいに到着したいと思っております。
Wi-Fi使わせていただけると大変助かります。もちろん有線でも可です。

**Comment by zaq1tomo** [comment]
@june29 メルカリからご提供させていただきますので、費用は大丈夫です！

**Comment by takei-shg** [comment]
遅れましたが今回もお手伝いできることありましたらお声がけくださいませ。

**Comment by june29** [comment]
https://github.com/hi-ether/community/issues/9#issue-317495077 のチェックリストを見直して、最新の状況を反映しておきました。あとは、当日の正午くらいに参加者向けのアナウンスを Slack でやろうと思います。「名刺を忘れずに持ってきてね！」などを全員に伝えたい。

あとは会場についての確認ということで、

- https://github.com/hi-ether/community/issues/9#issuecomment-394919507 に関して、A4 の印刷用紙を貼ったりしてよいですか？
- https://github.com/hi-ether/community/issues/9#issuecomment-395351997 に関して、動画配信用に使ってもよいネットワークはありますか？

あたりを @zaq1tomo さんにご確認いただきたいです。よろしくお願いします〜 :dash:

**Comment by zaq1tomo** [comment]
@june29 

> #9 (comment) に関して、A4 の印刷用紙を貼ったりしてよいですか？

イベント終了後に回収いただければ大丈夫です！

> #9 (comment) に関して、動画配信用に使ってもよいネットワークはありますか？

当日無料Wi-Fiをアナウンスします！

**Comment by june29** [comment]
@zaq1tomo さん、即答ありがとうございます :pray:

@yujikuroki @kazush-m 内容ご確認くださいませ〜〜〜 :dolphin:

**Comment by yujikuroki** [comment]
@zaq1tomo @june29 承知いたしました！ありがとうございます！🙇‍♂️

**Comment by june29** [comment]
当日の来場者向けアナウンスを出した :memo:

受付はメルカリさんから 1 人だしていただけるそうで、Hi-Ether 側からも 1 人いれば充分と聞いています。お話相手がたくさんいた方が待ち時間も楽しいでしょうから、2 人だしましょうかね :bulb:

名乗りを挙げてくれた人の中から 2 人を選出しようと思うので、現地で話して決めましょ〜 :dash:

**Comment by june29** [comment]
前日から当日にかけてだいぶバタバタしてしまいましたが、Meetup 自体はとても盛り上がってよかったと思います〜！みなさん、ありがとうございました。今回もおもしろかった。

今回はメルカリさんのご好意で食べ物・飲み物をご用意いただき、参加費無料での開催となりました。ですので「収支は ±0 です」という本コメントをもって、収支報告といたします :moneybag:

-----

あとは会場側の「参加者人数を把握する」「参加者名簿を作成する（名前+所属）」の状況をぼくが把握できていませんので @zaq1tomo さんにメンションさせてもらおうかしら、問題なく済んだようでしたら :white_check_mark: をお願いします :pray:

それだけ確認できましたら、この Issue も Close となります :poodle: :dash:
